---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[minifu::default]
    attributes:
      user:
        name: vagrant
        group: vagrant
        home: /home/vagrant
        fullname: Vagrant user
        email: vagrant@example.com
