name             'jfw-dotfiles-cookbook'
maintainer       'James F Wilkus'
maintainer_email 'jfwilkus@mac.com'
license          ''
description      'Installs/Configures jfw-dotfiles-cookbook'
long_description 'Installs/Configures jfw-dotfiles-cookbook'
version          '0.1.9-alpha.1'

depends 'homebrew'
depends 'yum'
depends 'yum-epel'
