name             'jfw-dotfiles-cookbook'
maintainer       'James F Wilkus'
maintainer_email 'jfwilkus@mac.com'
license          ''
description      'Installs/Configures my personal systems'
long_description 'Installs/Configures my personal systems'
version          '0.1.14'

depends 'homebrew'
depends 'yum'
depends 'yum-epel'
depends 'omnibus_updater'
